name: Release Extension

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Chrome Extension ZIP
        run: |
          zip chrome-extension.zip manifest.json content.js storage.js
          zip -r chrome-extension.zip icons

      - name: Create Firefox Extension ZIP
        run: |
          zip firefox-extension.zip manifest.json content.js storage.js
          zip -r firefox-extension.zip icons

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            chrome-extension.zip
            firefox-extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 